var methods = [
	{
		"name":"分类1",
		"methods":[
			{
				"type":"method",
				"name":"SetLCD3Char",
				"comment":"测试方法11",
				"icon":"img/for-end.png",
				"parameters":[
					{"type":"int","val":"0","name":"param1","comment":"参数1的注释"}, 
					{"type":"char","val":"a","name":"param2","comment":"参数2的注释"}
				],
				"returnInfo":{
					"type":"int",
				}
			},
			{
				"type":"method",
				"name":"SetLCD8Char",
				"comment":"测试方法12",
				"icon":"img/for-end.png",
				"parameters":[
					{"type":"int","val":"0","name":"param1","comment":"参数1的注释"},
					{"type":"int","val":"1","name":"param2","comment":"参数2的注释"}
				],
				"returnInfo":{
					"type":"void"
				}
			}
		]
	},
	{
		"name":"分类2",
		"methods":[
			{
				"type":"method",
				"name":"SetLCD3Char",
				"comment":"测试方法21",
				"icon":"img/for-end.png",
				"parameters":[
					{"type":"int","val":"0","name":"param1","comment":"参数1的注释"}, 
					{"type":"char","val":"a","name":"param2","comment":"参数2的注释"}, 
				],
				"returnInfo":{
					"type":"int",
				}
			},
			{
				"type":"method",
				"name":"SetLCD8Char",
				"comment":"测试方法22",
				"icon":"img/for-end.png",
				"parameters":[
					{"type":"int","val":"0","name":"param1","comment":"参数1的注释"}, 
					{"type":"int","val":"1","name":"param2","comment":"参数2的注释"}, 
				],
				"returnInfo":{
					"type":"void"
				}
			}
		]
	}
];
